### ISSUE TITLE
MAIN.py Not Running Because of Variable Issue

### ISSUE THREAD

**Issue by MichelleWellman** [Pocar-Lab/SiPMAnalysisApp#3]
When running MAIN.py and after selecting the "Xe" folder I get this error:
```UnboundLocalError: local variable 'df' referenced before assignment```
The bug is found on line 377

**Comment by atardigradestory** [comment]
Can't reproduce this on my environment. Try pulling a fresh copy from Github and see if it still happens.

**Comment by MichelleWellman** [comment]
I pulled a fresh copy and it doesn't seem to be happening anymore
