### ISSUE TITLE
Need the peaks.h5 file

### ISSUE THREAD

**Issue by MichelleWellman** [Pocar-Lab/SiPMAnalysisApp#4]
Getting an error where the script needs can't find the "peaks.h5" file. This makes sense because this file is no longer included in the applet package found here on GitHub. Is there a reason why this file is no longer part of the package?

I could try cheating and moving the "peaks.h5" file that I have from the old version of the app to the new folder. 

Alternatively, let me know if this is as simple as just commenting out the part of the script that calls for "peaks.h5"

**Comment by atardigradestory** [comment]
It was too big, I don't remember how I got you your first copy but yes just pull the old version nothing has changed in that.
